### ISSUE TITLE
main_process_first and local_main_process_first seem to not work when using the `flush` argument on print()

### ISSUE THREAD

**Issue by 984881878** [huggingface/accelerate#1183]
### System Info

```Shell
- `Accelerate` version: 0.17.0
- Platform: Linux-4.15.0-45-generic-x86_64-with-glibc2.27
- Python version: 3.9.7
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.13.1 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {}
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from accelerate import Accelerator

accelerator = Accelerator()
with accelerator.main_process_first():
    print(accelerator.process_index, accelerator.is_main_process, flush=True)
    # time.sleep(5)
```

### Expected behavior

```Shell
The behavior of main_process_first and local_main_process_first doesn't look the same as described in https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L723. In my case, it produces 
'''
2 False
1 False
3 False
0 True
'''
or
'''
2 False
0 True
1 False
3 False
'''
or something other.
```

**Comment by muellerzr** [comment]
@984881878 does it work with accelerate==0.16.0?

**Comment by 984881878** [comment]
> @984881878 does it work with accelerate==0.16.0?

Yes, it gets trouble after I upgrade accelerate to 0.17.0.
When I downgrade accelerate to 0.16.0, the snippets above output:
'''
0 True
23 False 
False
1 False
'''
'''
0 True
1 False
2 False
3 False
'''
'''
0 True
3 False
1 False
2 False
'''

my env now is:
'''
- `Accelerate` version: 0.16.0
- Platform: Linux-4.15.0-45-generic-x86_64-with-glibc2.27
- Python version: 3.9.7
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.13.1 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
'''

**Comment by muellerzr** [comment]
@984881878 the issue involves `flush=True`, so as a temporary "fix" just don't use `flush=True`. When trying with flush I was noticing it took quite a long time to print in the old version, I'll try and see what exactly could be the difference now.

**Comment by 984881878** [comment]
> @984881878 the issue involves `flush=True`, so as a temporary "fix" just don't use `flush=True`. When trying with flush I was noticing it took quite a long time to print in the old version, I'll try and see what exactly could be the difference now.
> 
> And you can then manually flush as well and have it work. Such that:
> 
> ```python
> from accelerate import Accelerator
> import sys
> 
> accelerator = Accelerator()
> 
> with accelerator.main_process_first():
>     print(f'Process: {accelerator.process_index}, {accelerator.is_main_process}')
>     sys.stdout.flush()
> ```

I tried manually flush the out buffer as you said, but it still did not work as I expected. 😂😂😂

**Comment by muellerzr** [comment]
Sorry to hear that did not work for you, it worked for me hence the suggestion. I'll look into this this week.

**Comment by 984881878** [comment]
> Sorry to hear that did not work for you, it worked for me hence the suggestion. I'll look into this this week.

```python
import os
from accelerate import Accelerator
accelerator = Accelerator()
with accelerator.local_main_process_first():
    os.makedirs('tmp', exist_ok=not accelerator.is_local_main_process)
```
Does this work on your machine? It didn't work on my machine anyway.

**Comment by muellerzr** [comment]
@984881878 this will probably be fixed via https://github.com/huggingface/accelerate/pull/1304

**Comment by 984881878** [comment]
> @984881878 this will probably be fixed via #1304

Hi, it seems not to be fixed yet, though I installed the latest dev version of Accelerate.

**Comment by muellerzr** [comment]
It's not on dev, it's in their PR. So you would need to try via:

`pip install git+https://github.com/flukeskywalker/accelerate/@fix-1303-main_proces_first`

**Comment by 984881878** [comment]
@muellerzr Thanks for your reminder. But it still doesn't work for me.
