### ISSUE TITLE
SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types

### ISSUE THREAD

**Issue by ChenchaoZhao** [huggingface/accelerate#980]
### System Info

```Shell
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 1102, in launch_command
    sagemaker_launcher(defaults, args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 907, in sagemaker_launcher
    hyperparameters = _convert_nargs_to_dict(args.training_script_args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 853, in _convert_nargs_to_dict
    "SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types"
ValueError: SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/diffusers/tree/v0.11.0/examples/unconditional_image_generation

accelerate launch train_unconditional.py \
  --dataset_name="huggan/flowers-102-categories" \
  --resolution=64 \
  --output_dir="ddpm-ema-flowers-64" \
  --train_batch_size=16 \
  --num_epochs=100 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision=no

### Expected behavior

```Shell
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 1102, in launch_command
    sagemaker_launcher(defaults, args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 907, in sagemaker_launcher
    hyperparameters = _convert_nargs_to_dict(args.training_script_args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 853, in _convert_nargs_to_dict
    "SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types"
ValueError: SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types
```

**Comment by sgugger** [comment]
I don't think you can use that script out of the box on SageMaker since it makes use of argparse with `store_true` arguments and those are not supported on SageMaker.

cc @philschmid if you have more to share on this.

**Comment by ChenchaoZhao** [comment]
> 
I was following this doc https://huggingface.co/docs/accelerate/v0.15.0/en/usage_guides/sagemaker#prepare-a-accelerate-finetuning-script

I configured `accelerate` to run on Sagemaker. Then I ran 
`accelerate launch path_to_script.py --args_to_the_script`

**Comment by philschmid** [comment]
As mentioned by @sgugger you have to modify the `argsparser` arguments from `store_true` to `boolean` and explicitly pass them. 
See SageMaker documentation: 
> Note that SageMaker doesn’t support argparse actions. If you want to use, for example, boolean hyperparameters, you need to specify type as bool in your script and provide an explicit True or False value for this hyperparameter when you create your estimator.

**Comment by ChenchaoZhao** [comment]
> As mentioned by @sgugger you have to modify the `argsparser` arguments from `store_true` to `boolean` and explicitly pass them. See SageMaker documentation:
> 
> > Note that SageMaker doesn’t support argparse actions. If you want to use, for example, boolean hyperparameters, you need to specify type as bool in your script and provide an explicit True or False value for this hyperparameter when you create your estimator.

Which means it’s a bug of the sagemaker accelerate launcher. Any ongoing efforts to fix this bug? Otherwise I could try to fix it and PR.

**Comment by philschmid** [comment]
> Which means it’s a bug of the sagemaker accelerate launcher. Any ongoing efforts to fix this bug? Otherwise I could try to fix it and PR.

I wouldn't say that's a bug of accelerate. It has been a missing feature for SageMaker for years, and to solve this, you have to adjust the scripts from `store_true` to `boolean`.

**Comment by ChenchaoZhao** [comment]
After replacing `store_*` to `bool` type the script still did not run. If I remove all the training args from the `train.py` script, the it can train (after some struggle in the `transformers` dependency issues). The real issue, I think, was `accelerate launch` did not parse the custom args correctly.

**Comment by pacman100** [comment]
Hello @ChenchaoZhao,

Can you please refer the examples here: https://github.com/huggingface/notebooks/tree/main/sagemaker/22_accelerate_sagemaker_examples and check if those work without any issues. If so, then check how arguments are being handled there?

**Comment by somudro** [comment]
@pacman100 I'm having the same issue as @ChenchaoZhao . I'm trying the seg2seq example in https://github.com/huggingface/notebooks/tree/main/sagemaker/22_accelerate_sagemaker_examples when I run `bash launch.sh` I get the same issue (also referenced here https://github.com/huggingface/accelerate/issues/898):

(diffusers) somudro@hippopotamus:~/ws/notebooks/sagemaker/22_accelerate_sagemaker_examples/src/seq2seq$ bash launch.sh
Traceback (most recent call last):
  File "/home/somudro/anaconda3/envs/diffusers/bin/accelerate", line 10, in <module>
    sys.exit(main())
  File "/home/somudro/anaconda3/envs/diffusers/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/somudro/anaconda3/envs/diffusers/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1071, in launch_command
    if args.use_cpu and args.num_processes > 1:
AttributeError: 'Namespace' object has no attribute 'use_cpu'

accelerate is 0.15.0 in conda

**Comment by pacman100** [comment]
Hello @somudro, the above PR should resolve the issue that you are facing

**Comment by samirop** [comment]
This is supposed to be solved, but I'm getting the same errors with the last version of accelerate. Also, I checked the aforementioned PR, and it doesn't seem to address these issues. 
First, I was getting the "'Namespace' object has no attribute 'use_cpu' #898" error, which I could fix by manually adding a use_cpu argument in the launch.py file. After this, I started getting the store_true error. 
Any clues on how to proceed with this?

**Comment by rohit901** [comment]
Hi @pacman100,

Im following example script in https://github.com/huggingface/notebooks/tree/main/sagemaker/22_accelerate_sagemaker_examples/src/text-classification

and have made changes in my train.py script to remove all action=store_true, and action=store_false arguments, and passed bool values explicitly. However, I'm still facing the issues on my custom script.

my launch.sh:
```
export MODEL_NAME="xxx"

accelerate launch --config_file accelerate_config.yaml train.py \
    --pretrained_teacher_model=$MODEL_NAME \
    --mixed_precision=fp16 \
    --resolution=512 \
    --learning_rate=1e-6 --loss_type="huber" --ema_decay=0.95 --adam_weight_decay=0.0 \
    --max_train_steps=10727607 \
    --max_train_samples=10727607 \
    --dataloader_num_workers=8 \
    --validation_steps=200 \
    --checkpointing_steps=200 --checkpoints_total_limit=10 \
    --train_batch_size=12 \
    --gradient_checkpointing=True \
    --enable_xformers_memory_efficient_attention=True \
    --gradient_accumulation_steps=1 \
    --use_8bit_adam=True \
    --resume_from_checkpoint=latest \
    --seed=453645634
```

Im getting this error:
`ValueError: SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types
`
checking the code, it seems in accelerate->utils->launch.py
in this function:
def `_convert_nargs_to_dict(nargs)`

the nargs argument is like this:
['--pretrained_teacher_model=damo-vilab/text-to-video-ms-1.7b', '--mixed_precision=fp16', '--resolution=512', '--learning_rate=1e-6', '--loss_type=huber', '--ema_decay=0.95', '--adam_weight_decay=0.0', '--max_train_steps=10727607', '--max_train_samples=10727607', '--dataloader_num_workers=8', '--validation_steps=200', '--checkpointing_steps=200', '--checkpoints_total_limit=10', '--train_batch_size=12', '--gradient_checkpointing=True', '--enable_xformers_memory_efficient_attention=True', '--gradient_accumulation_steps=1', '--use_8bit_adam=True', '--resume_from_checkpoint=latest', '--seed=453645634']

and the logic in the code throws off ValueError as consecutive flags have "--" present in them.. 

Could you help me understand, whats happening over here, and where is the issue?

**Comment by rohit901** [comment]
Removing "=" from above argument call, and directly passing in with space seemed to fix the issue. But I think it would be nice if it can also support the above way of passing arguments?

**Comment by muellerzr** [comment]
@rohit901 does the trace stem from sagemaker or from accelerate? (The full stack trace). Wondering if we can write a test that doesn't rely on sagemaker directly basically

**Comment by rohit901** [comment]
hi @muellerzr 
the entire logs are as follows:
```
/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/torch/cuda/__init__.py:628: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/rohit.bharadwaj/.config/sagemaker/config.yaml
Configuring Amazon SageMaker environment
Converting Arguments to Hyperparameters
Traceback (most recent call last):
  File "/home/rohit.bharadwaj/.conda/envs/LCM/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1021, in launch_command
    sagemaker_launcher(defaults, args)
  File "/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/accelerate/commands/launch.py", line 836, in sagemaker_launcher
    args, sagemaker_inputs = prepare_sagemager_args_inputs(sagemaker_config, args)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/accelerate/utils/launch.py", line 433, in prepare_sagemager_args_inputs
    hyperparameters = _convert_nargs_to_dict(args.training_script_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rohit.bharadwaj/.conda/envs/LCM/lib/python3.11/site-packages/accelerate/utils/launch.py", line 387, in _convert_nargs_to_dict
    raise ValueError(
ValueError: SageMaker doesn’t support argparse actions for `store_true` or `store_false`. Please define explicit types
```

I believe the trace stems from accelerate itself.
